apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - files:
      - prometheus-ksm.yaml.tmpl=prometheus-ksm.yaml.tmpl
    name: alert-templates-prometheus-ksm

patches:
  - path: volume.yaml
