apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - files:
      - all.yaml.tmpl=all.yaml.tmpl
      - logging.yaml.tmpl=logging.yaml.tmpl
      - by_namespace.yaml.tmpl
    name: alert-templates-common

patches:
  - path: volume.yaml
