apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - files:
      - all.yaml.tmpl=all.yaml.tmpl
      - logging.yaml.tmpl=logging.yaml.tmpl
      - container.yaml.tmpl
      - missing_replicas.yaml.tmpl
      - namespace_sync.yaml.tmpl
      - storage.yaml.tmpl
      - terraform_sync.yaml.tmpl
      - vault.yaml.tmpl
    name: alert-templates-common

patches:
  - path: volume.yaml
